### ISSUE TITLE
Potential trust issues

### ISSUE THREAD

**Issue by ekalchev** [mgaffigan/passdata#1]
Isn't it a problem that ephemeral code signing certificate that is created to carry the payload is not trusted? I guess that will upset some antivirus software?

**Comment by mgaffigan** [comment]
I'm not aware of any AV platforms that object to untrusted signatures (when there is a good signature present). If you have an example, please name it. Multiple signatures are used by design as a compatibility mechanism.

Some security platforms do operate on the hash of the file, which does prevent trust being accumulated - but that's unavoidable for any solution which embeds data in the file. URL activation, ClickOnce arguments, or using the file name to pass data can be alternatives to avoid embedded data, but those all have substantial limitations.

**Comment by ekalchev** [comment]
Thanks!

**Comment by mgaffigan** [comment]
Of course. Please feel free to re-open if you find an example.
